### ISSUE TITLE
sd card support

### ISSUE THREAD

**Issue by ahjolinna** [lukedirtwalker/cutespotify#11] opened 2015-01-04 17:57 UTC
It would be nice to have a option to choose where cutespotify saves offline data/songs.

**Comment by sandsmark** [comment] 2015-02-24 13:55
you should be able to do this by changing the path in the config file.

I tried to make it possible to change this at runtime, but closing and re-opening the spotify session was not trivial, and having to restart the app was ugly, so I kind of gave up.

**Comment by lukedirtwalker** [comment] 2015-02-24 13:58
libspotify would allow to move the data. But then again I don't know how long this takes. While adapting the path would be easy the moving is the reason why I didn't do it yet.

**Comment by sandsmark** [comment] 2015-02-24 14:10
well, I was just going to nuke the old cache and force it to re-download all the data, but moving sounds better. :-)

**Comment by lukedirtwalker** [comment] 2015-02-24 14:18
Hum actually I'm wrong there is no such function, I confused it with the bitrate function which can resync the cache (https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#ga4bba5f828d6c87692f2c355cc8f07c61)

**Comment by BonoNL** [comment] 2015-04-29 20:11
Would be a nice option. Would make the app be faster with adapting the SD card then Sailfish itself :)

**Comment by lolli78** [comment] 2015-08-11 06:53
As SD cards are getting cheaper and Jolla Phone only has 16 GB internal memory, this would be a great option (even with deleting and re-downloading all offline music).

**Comment by lukedirtwalker** [comment] 2015-08-11 06:55
Good those are now enough votes. I will check it out, this weekend.

**Comment by lolli78** [comment] 2015-08-11 07:25
Great news! Thanks!

**Comment by florianwittmann** [comment] 2015-08-11 10:58
Awesome news! :+1:

**Closed as completed** 2015-08-15 20:35 UTC
Labels: enhancement

**Comment by lukedirtwalker** [comment] 2015-08-15 20:36
Please test the following version: https://drive.google.com/file/d/0B-KOnAfO-Ux8MnE0N2ZQQm5zRG8/view?usp=sharing

**Comment by lolli78** [comment] 2015-08-18 08:08
Thanks for this enhancement. It works perfectly, but after the first restart all playlists in the main view were shown twice. Don't know how to reproduce this.

**Comment by lukedirtwalker** [comment] 2015-08-18 09:07
@lolli78 Oh that's an old problem which is known. Just restart again and it should work :P

**Comment by BonoNL** [comment] 2015-08-18 18:41
Wanted to test it but my SD card seemed to be disappeared.

Well that is whats happening after nearly 2 years of not using it, I probably lend it to someone.

Not able to test it tomorrow.
